---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
    spec:
      {{- if .Values.controller.image.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.controller.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - /manager
        {{- if .Values.controller.image.imagePullPolicy }}
        imagePullPolicy: {{ .Values.controller.image.imagePullPolicy }}
        {{- end }}
        args:
        - "--leader-elect"
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=:8443"
        image: {{ .Values.controller.image.prefix }}/{{ .Values.controller.image.name }}:{{ .Values.controller.image.tag }}
        env:
        - name: MANAGER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DYNAMIC_WEBHOOK_NAME
          value: {{ .Release.Name }}-dynamic-remotesyncer-webhook
        name: manager
        securityContext: {{ toYaml .Values.controller.securityContext | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ toYaml .Values.controller.resources | nindent 10 }}
        ports:
        - containerPort: 9443
          name: webhook-svc
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: {{ .Release.Name }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- if .Values.controller.tolerations }}
      tolerations: {{ toYaml .Values.controller.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.certmanager.webhook.certificate.secret }}