apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: {{ .Values.webhook.services.crd }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Values.webhook.services.crd }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: webhook-pusher-service
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: dams
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: webhook-pusher-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9444
  selector:
    control-plane: controller-manager