apiVersion: syngit.syngit.io/v2alpha2
kind: RemoteUser
metadata:
  labels:
    app.kubernetes.io/name: remoteuser
    app.kubernetes.io/instance: remoteuser-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remoteuser-sample2
  namespace: test
spec:
  gitBaseDomainFQDN: "gitlab.com"
  testAuthentication: true
  email: dassieu.damien@gmail.com
  secretRef:
    name: secret-basic-auth
  ownRemoteUserBinding: false
