apiVersion: syngit.syngit.io/v1alpha2
kind: RemoteSyncer
metadata:
  labels:
    app.kubernetes.io/name: remotesyncer
    app.kubernetes.io/instance: remotesyncer-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remotesyncer-sample
  namespace: test
spec:
  remoteRepository: ""
  branch: second-main
  commitProcess: CommitApply
# bypassInterceptionSubjects:
    #- name: kubernetes-admin
    #  kind: User
  authorizedUsers:
    - name: owned-rub-kubernetes-admin
  defaultUnauthorizedUserMode: Block
  excludedFields:
    - metadata.managedFields
    - metadata.creationTimestamp
    - metadata.annotations.[kubectl.kubernetes.io/last-applied-configuration]
    - metadata.uid
    - metadata.resourceVersion
  rootPath: "root-path"
  includedResources:
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["configmaps", "pods"]
        operations: ["CREATE", "UPDATE", "DELETE"]
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["ingresses"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        #repoPath: "oui/config"
