## Append samples of your project ##
resources:
- syngit_v1alpha4_remoteuserbinding.yaml
- syngit_v1alpha4_remoteuser.yaml
- syngit_v1alpha4_remotesyncer.yaml
- syngit_v1beta1_remoteuser.yaml
- syngit_v1beta1_remoteuserbinding.yaml
- syngit_v1beta1_remotesyncer.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
