webhook:
  certmanager:
    enable: true
    certificate:
      name: webhook-cert
      secret: webhook-server-cert

controller:
  image:
    prefix: ghcr.io/syngit-org
    name: syngit
    tag: 0.0.3

  securityContext:
    runAsUser: 1000
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    seccompProfile:
      type: "RuntimeDefault"
    capabilities:
      drop:
      - "ALL"
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  tolerations: []

  metrics:
    enable: false
    bindAddress: 127.0.0.1:8080

  rbacProxy:
    enable: false
    upstreamAddress: http://127.0.0.1:8080/
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      seccompProfile:
        type: "RuntimeDefault"
      capabilities:
        drop:
        - "ALL"

monitoring:
  enable: false

installCRD: true

configuration:
  gitlab: true
  github: true
  bitbucket: true
