---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remotesyncers-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-remotesyncers-editor-role
rules:
- apiGroups:
  - syngit.syngit.io
  resources:
  - remotesyncerss
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.syngit.io
  resources:
  - remotesyncerss/status
  verbs:
  - get
