apiVersion: syngit.syngit.io/v1alpha2
kind: RemoteUserBinding
metadata:
  labels:
    app.kubernetes.io/name: remoteuserbinding
    app.kubernetes.io/instance: remoteuserbinding-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remoteuserbinding-sample
  namespace: test
spec:
