name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 #v4.1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build chart dependencies
        run: |
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm dependency update "$chart"
            fi
          done

      - name: Add Helm repositories
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          
      - name: Package chart
        run: |
          helm package charts/${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 #v2.4.1
        with:
          prerelease: true
          generate_release_notes: true
          append_body: true
          tag_name: ${{ github.ref_name }}
          files: "*.tgz"
      
      - name: Upload chart package and update Helm index
        run: |
          TAG_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
  
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git stash
          git checkout gh-pages

          if [ -f index.yaml ]; then
            helm repo index . --url $TAG_URL --merge index.yaml
          else
            helm repo index . --url $TAG_URL
          fi

          git add index.yaml
          git commit -m "feat(release): Update Helm index for the ${CHART_VERSION} version" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"